name: Create Tag on PR to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Tag
      run: |
        TAG_NAME=$(echo "${{ github.event.pull_request.body }}" | grep -oP 'Enter the desired tag or leave blank: \K\S+')
        if [[ ! -z "$TAG_NAME" ]]; then
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
        fi